---
kind: pipeline
name: amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.6.0
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: integration-test
    image: rancher/rancher:v2.9-head
    pull: always
    privileged: true
    commands:
      - curl --cacert /etc/ssl/ca-bundle.pem -sL https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz | tar xvzf - -C /usr/local/bin --strip-components=1
      - scripts/integration-test

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-amd64.txt
      checksum_flatten: true
      files:
        - "dist/artifacts/*"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/rancher-webhook"
      tag: "${DRONE_TAG}-amd64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: arm64
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rancher/dapper:v0.6.0
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: integration-test
    image: rancher/rancher:v2.9-head
    pull: always
    privileged: true
    commands:
      - curl --cacert /etc/ssl/ca-bundle.pem -sL https://get.helm.sh/helm-v3.13.3-linux-arm64.tar.gz | tar xvzf - -C /usr/local/bin --strip-components=1
      - scripts/integration-test

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-arm64.txt
      checksum_flatten: true
      files:
        - "dist/artifacts/*"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/rancher-webhook"
      tag: "${DRONE_TAG}-arm64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: manifest
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: manifest
    image: plugins/manifest:1.4.0
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
      target: "rancher/rancher-webhook:${DRONE_TAG}"
      template: "rancher/rancher-webhook:${DRONE_TAG}-ARCH"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

depends_on:
  - amd64
  - arm64

---
kind: pipeline
name: fossa
type: docker

steps:
  - name: fossa
    image: rancher/drone-fossa:latest
    failure: ignore
    settings:
      api_key:
        from_secret: FOSSA_API_KEY
      when:
        instance:
          - drone-publish.rancher.io
