---
kind: pipeline
name: arm64
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rancher/dapper:v0.6.0
    commands:
      - uname -a
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: integration-test
    image: rancher/rancher:v2.9-head
    pull: always
    privileged: true
    commands:
      - zypper -n install helm
      - scripts/integration-test

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-arm64.txt
      checksum_flatten: true
      files:
        - "dist/artifacts/*"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/rancher-webhook"
      tag: "${DRONE_TAG}-arm64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: fossa
type: docker

steps:
  - name: fossa
    image: rancher/drone-fossa:latest
    failure: ignore
    settings:
      api_key:
        from_secret: FOSSA_API_KEY
      when:
        instance:
          - drone-publish.rancher.io
