kind: Service
apiVersion: v1
metadata:
  name: rancher-webhook
  namespace: cattle-system
  annotations:
    need-a-cert.cattle.io/secret-name: cattle-webhook-ca
spec:
  ports:
  - port: 443
    targetPort: {{ .Values.port | default 9443 }}
    protocol: TCP
    name: https
  selector:
    app: rancher-webhook
