// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/webhook/pkg/generated/controllers/management.cattle.io/v3 (interfaces: ProjectRoleTemplateBindingController,ProjectRoleTemplateBindingClient,ProjectRoleTemplateBindingCache)

// Package fakes is a generated GoMock package.
package fakes

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	v30 "github.com/rancher/webhook/pkg/generated/controllers/management.cattle.io/v3"
	generic "github.com/rancher/wrangler/pkg/generic"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MockProjectRoleTemplateBindingController is a mock of ProjectRoleTemplateBindingController interface.
type MockProjectRoleTemplateBindingController struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRoleTemplateBindingControllerMockRecorder
}

// MockProjectRoleTemplateBindingControllerMockRecorder is the mock recorder for MockProjectRoleTemplateBindingController.
type MockProjectRoleTemplateBindingControllerMockRecorder struct {
	mock *MockProjectRoleTemplateBindingController
}

// NewMockProjectRoleTemplateBindingController creates a new mock instance.
func NewMockProjectRoleTemplateBindingController(ctrl *gomock.Controller) *MockProjectRoleTemplateBindingController {
	mock := &MockProjectRoleTemplateBindingController{ctrl: ctrl}
	mock.recorder = &MockProjectRoleTemplateBindingControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRoleTemplateBindingController) EXPECT() *MockProjectRoleTemplateBindingControllerMockRecorder {
	return m.recorder
}

// AddGenericHandler mocks base method.
func (m *MockProjectRoleTemplateBindingController) AddGenericHandler(arg0 context.Context, arg1 string, arg2 generic.Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddGenericHandler", arg0, arg1, arg2)
}

// AddGenericHandler indicates an expected call of AddGenericHandler.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) AddGenericHandler(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGenericHandler", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).AddGenericHandler), arg0, arg1, arg2)
}

// AddGenericRemoveHandler mocks base method.
func (m *MockProjectRoleTemplateBindingController) AddGenericRemoveHandler(arg0 context.Context, arg1 string, arg2 generic.Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddGenericRemoveHandler", arg0, arg1, arg2)
}

// AddGenericRemoveHandler indicates an expected call of AddGenericRemoveHandler.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) AddGenericRemoveHandler(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGenericRemoveHandler", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).AddGenericRemoveHandler), arg0, arg1, arg2)
}

// Cache mocks base method.
func (m *MockProjectRoleTemplateBindingController) Cache() v30.ProjectRoleTemplateBindingCache {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cache")
	ret0, _ := ret[0].(v30.ProjectRoleTemplateBindingCache)
	return ret0
}

// Cache indicates an expected call of Cache.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) Cache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cache", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).Cache))
}

// Create mocks base method.
func (m *MockProjectRoleTemplateBindingController) Create(arg0 *v3.ProjectRoleTemplateBinding) (*v3.ProjectRoleTemplateBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*v3.ProjectRoleTemplateBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockProjectRoleTemplateBindingController) Delete(arg0, arg1 string, arg2 *v1.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).Delete), arg0, arg1, arg2)
}

// Enqueue mocks base method.
func (m *MockProjectRoleTemplateBindingController) Enqueue(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Enqueue", arg0, arg1)
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) Enqueue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).Enqueue), arg0, arg1)
}

// EnqueueAfter mocks base method.
func (m *MockProjectRoleTemplateBindingController) EnqueueAfter(arg0, arg1 string, arg2 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnqueueAfter", arg0, arg1, arg2)
}

// EnqueueAfter indicates an expected call of EnqueueAfter.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) EnqueueAfter(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueAfter", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).EnqueueAfter), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockProjectRoleTemplateBindingController) Get(arg0, arg1 string, arg2 v1.GetOptions) (*v3.ProjectRoleTemplateBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v3.ProjectRoleTemplateBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).Get), arg0, arg1, arg2)
}

// GroupVersionKind mocks base method.
func (m *MockProjectRoleTemplateBindingController) GroupVersionKind() schema.GroupVersionKind {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupVersionKind")
	ret0, _ := ret[0].(schema.GroupVersionKind)
	return ret0
}

// GroupVersionKind indicates an expected call of GroupVersionKind.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) GroupVersionKind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupVersionKind", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).GroupVersionKind))
}

// Informer mocks base method.
func (m *MockProjectRoleTemplateBindingController) Informer() cache.SharedIndexInformer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Informer")
	ret0, _ := ret[0].(cache.SharedIndexInformer)
	return ret0
}

// Informer indicates an expected call of Informer.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) Informer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Informer", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).Informer))
}

// List mocks base method.
func (m *MockProjectRoleTemplateBindingController) List(arg0 string, arg1 v1.ListOptions) (*v3.ProjectRoleTemplateBindingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*v3.ProjectRoleTemplateBindingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).List), arg0, arg1)
}

// OnChange mocks base method.
func (m *MockProjectRoleTemplateBindingController) OnChange(arg0 context.Context, arg1 string, arg2 v30.ProjectRoleTemplateBindingHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnChange", arg0, arg1, arg2)
}

// OnChange indicates an expected call of OnChange.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) OnChange(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChange", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).OnChange), arg0, arg1, arg2)
}

// OnRemove mocks base method.
func (m *MockProjectRoleTemplateBindingController) OnRemove(arg0 context.Context, arg1 string, arg2 v30.ProjectRoleTemplateBindingHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnRemove", arg0, arg1, arg2)
}

// OnRemove indicates an expected call of OnRemove.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) OnRemove(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnRemove", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).OnRemove), arg0, arg1, arg2)
}

// Patch mocks base method.
func (m *MockProjectRoleTemplateBindingController) Patch(arg0, arg1 string, arg2 types.PatchType, arg3 []byte, arg4 ...string) (*v3.ProjectRoleTemplateBinding, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(*v3.ProjectRoleTemplateBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) Patch(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).Patch), varargs...)
}

// Update mocks base method.
func (m *MockProjectRoleTemplateBindingController) Update(arg0 *v3.ProjectRoleTemplateBinding) (*v3.ProjectRoleTemplateBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(*v3.ProjectRoleTemplateBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).Update), arg0)
}

// Updater mocks base method.
func (m *MockProjectRoleTemplateBindingController) Updater() generic.Updater {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updater")
	ret0, _ := ret[0].(generic.Updater)
	return ret0
}

// Updater indicates an expected call of Updater.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) Updater() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updater", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).Updater))
}

// Watch mocks base method.
func (m *MockProjectRoleTemplateBindingController) Watch(arg0 string, arg1 v1.ListOptions) (watch.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", arg0, arg1)
	ret0, _ := ret[0].(watch.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockProjectRoleTemplateBindingControllerMockRecorder) Watch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockProjectRoleTemplateBindingController)(nil).Watch), arg0, arg1)
}

// MockProjectRoleTemplateBindingClient is a mock of ProjectRoleTemplateBindingClient interface.
type MockProjectRoleTemplateBindingClient struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRoleTemplateBindingClientMockRecorder
}

// MockProjectRoleTemplateBindingClientMockRecorder is the mock recorder for MockProjectRoleTemplateBindingClient.
type MockProjectRoleTemplateBindingClientMockRecorder struct {
	mock *MockProjectRoleTemplateBindingClient
}

// NewMockProjectRoleTemplateBindingClient creates a new mock instance.
func NewMockProjectRoleTemplateBindingClient(ctrl *gomock.Controller) *MockProjectRoleTemplateBindingClient {
	mock := &MockProjectRoleTemplateBindingClient{ctrl: ctrl}
	mock.recorder = &MockProjectRoleTemplateBindingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRoleTemplateBindingClient) EXPECT() *MockProjectRoleTemplateBindingClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectRoleTemplateBindingClient) Create(arg0 *v3.ProjectRoleTemplateBinding) (*v3.ProjectRoleTemplateBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*v3.ProjectRoleTemplateBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProjectRoleTemplateBindingClientMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectRoleTemplateBindingClient)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockProjectRoleTemplateBindingClient) Delete(arg0, arg1 string, arg2 *v1.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectRoleTemplateBindingClientMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectRoleTemplateBindingClient)(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockProjectRoleTemplateBindingClient) Get(arg0, arg1 string, arg2 v1.GetOptions) (*v3.ProjectRoleTemplateBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v3.ProjectRoleTemplateBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProjectRoleTemplateBindingClientMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProjectRoleTemplateBindingClient)(nil).Get), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockProjectRoleTemplateBindingClient) List(arg0 string, arg1 v1.ListOptions) (*v3.ProjectRoleTemplateBindingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*v3.ProjectRoleTemplateBindingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectRoleTemplateBindingClientMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectRoleTemplateBindingClient)(nil).List), arg0, arg1)
}

// Patch mocks base method.
func (m *MockProjectRoleTemplateBindingClient) Patch(arg0, arg1 string, arg2 types.PatchType, arg3 []byte, arg4 ...string) (*v3.ProjectRoleTemplateBinding, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(*v3.ProjectRoleTemplateBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockProjectRoleTemplateBindingClientMockRecorder) Patch(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockProjectRoleTemplateBindingClient)(nil).Patch), varargs...)
}

// Update mocks base method.
func (m *MockProjectRoleTemplateBindingClient) Update(arg0 *v3.ProjectRoleTemplateBinding) (*v3.ProjectRoleTemplateBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(*v3.ProjectRoleTemplateBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProjectRoleTemplateBindingClientMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectRoleTemplateBindingClient)(nil).Update), arg0)
}

// Watch mocks base method.
func (m *MockProjectRoleTemplateBindingClient) Watch(arg0 string, arg1 v1.ListOptions) (watch.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", arg0, arg1)
	ret0, _ := ret[0].(watch.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockProjectRoleTemplateBindingClientMockRecorder) Watch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockProjectRoleTemplateBindingClient)(nil).Watch), arg0, arg1)
}

// MockProjectRoleTemplateBindingCache is a mock of ProjectRoleTemplateBindingCache interface.
type MockProjectRoleTemplateBindingCache struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRoleTemplateBindingCacheMockRecorder
}

// MockProjectRoleTemplateBindingCacheMockRecorder is the mock recorder for MockProjectRoleTemplateBindingCache.
type MockProjectRoleTemplateBindingCacheMockRecorder struct {
	mock *MockProjectRoleTemplateBindingCache
}

// NewMockProjectRoleTemplateBindingCache creates a new mock instance.
func NewMockProjectRoleTemplateBindingCache(ctrl *gomock.Controller) *MockProjectRoleTemplateBindingCache {
	mock := &MockProjectRoleTemplateBindingCache{ctrl: ctrl}
	mock.recorder = &MockProjectRoleTemplateBindingCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRoleTemplateBindingCache) EXPECT() *MockProjectRoleTemplateBindingCacheMockRecorder {
	return m.recorder
}

// AddIndexer mocks base method.
func (m *MockProjectRoleTemplateBindingCache) AddIndexer(arg0 string, arg1 v30.ProjectRoleTemplateBindingIndexer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddIndexer", arg0, arg1)
}

// AddIndexer indicates an expected call of AddIndexer.
func (mr *MockProjectRoleTemplateBindingCacheMockRecorder) AddIndexer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIndexer", reflect.TypeOf((*MockProjectRoleTemplateBindingCache)(nil).AddIndexer), arg0, arg1)
}

// Get mocks base method.
func (m *MockProjectRoleTemplateBindingCache) Get(arg0, arg1 string) (*v3.ProjectRoleTemplateBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*v3.ProjectRoleTemplateBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProjectRoleTemplateBindingCacheMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProjectRoleTemplateBindingCache)(nil).Get), arg0, arg1)
}

// GetByIndex mocks base method.
func (m *MockProjectRoleTemplateBindingCache) GetByIndex(arg0, arg1 string) ([]*v3.ProjectRoleTemplateBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIndex", arg0, arg1)
	ret0, _ := ret[0].([]*v3.ProjectRoleTemplateBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIndex indicates an expected call of GetByIndex.
func (mr *MockProjectRoleTemplateBindingCacheMockRecorder) GetByIndex(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIndex", reflect.TypeOf((*MockProjectRoleTemplateBindingCache)(nil).GetByIndex), arg0, arg1)
}

// List mocks base method.
func (m *MockProjectRoleTemplateBindingCache) List(arg0 string, arg1 labels.Selector) ([]*v3.ProjectRoleTemplateBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*v3.ProjectRoleTemplateBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectRoleTemplateBindingCacheMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectRoleTemplateBindingCache)(nil).List), arg0, arg1)
}
