// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/webhook/pkg/generated/controllers/management.cattle.io/v3 (interfaces: RoleTemplateCache)

// Package fakes is a generated GoMock package.
package fakes

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	v30 "github.com/rancher/webhook/pkg/generated/controllers/management.cattle.io/v3"
	labels "k8s.io/apimachinery/pkg/labels"
)

// MockRoleTemplateCache is a mock of RoleTemplateCache interface.
type MockRoleTemplateCache struct {
	ctrl     *gomock.Controller
	recorder *MockRoleTemplateCacheMockRecorder
}

// MockRoleTemplateCacheMockRecorder is the mock recorder for MockRoleTemplateCache.
type MockRoleTemplateCacheMockRecorder struct {
	mock *MockRoleTemplateCache
}

// NewMockRoleTemplateCache creates a new mock instance.
func NewMockRoleTemplateCache(ctrl *gomock.Controller) *MockRoleTemplateCache {
	mock := &MockRoleTemplateCache{ctrl: ctrl}
	mock.recorder = &MockRoleTemplateCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleTemplateCache) EXPECT() *MockRoleTemplateCacheMockRecorder {
	return m.recorder
}

// AddIndexer mocks base method.
func (m *MockRoleTemplateCache) AddIndexer(arg0 string, arg1 v30.RoleTemplateIndexer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddIndexer", arg0, arg1)
}

// AddIndexer indicates an expected call of AddIndexer.
func (mr *MockRoleTemplateCacheMockRecorder) AddIndexer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIndexer", reflect.TypeOf((*MockRoleTemplateCache)(nil).AddIndexer), arg0, arg1)
}

// Get mocks base method.
func (m *MockRoleTemplateCache) Get(arg0 string) (*v3.RoleTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*v3.RoleTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoleTemplateCacheMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoleTemplateCache)(nil).Get), arg0)
}

// GetByIndex mocks base method.
func (m *MockRoleTemplateCache) GetByIndex(arg0, arg1 string) ([]*v3.RoleTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIndex", arg0, arg1)
	ret0, _ := ret[0].([]*v3.RoleTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIndex indicates an expected call of GetByIndex.
func (mr *MockRoleTemplateCacheMockRecorder) GetByIndex(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIndex", reflect.TypeOf((*MockRoleTemplateCache)(nil).GetByIndex), arg0, arg1)
}

// List mocks base method.
func (m *MockRoleTemplateCache) List(arg0 labels.Selector) ([]*v3.RoleTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]*v3.RoleTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRoleTemplateCacheMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoleTemplateCache)(nil).List), arg0)
}
