// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/wrangler/pkg/generated/controllers/rbac/v1 (interfaces: RoleCache)

// Package fakes is a generated GoMock package.
package fakes

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/rancher/wrangler/pkg/generated/controllers/rbac/v1"
	v10 "k8s.io/api/rbac/v1"
	labels "k8s.io/apimachinery/pkg/labels"
)

// MockRoleCache is a mock of RoleCache interface.
type MockRoleCache struct {
	ctrl     *gomock.Controller
	recorder *MockRoleCacheMockRecorder
}

// MockRoleCacheMockRecorder is the mock recorder for MockRoleCache.
type MockRoleCacheMockRecorder struct {
	mock *MockRoleCache
}

// NewMockRoleCache creates a new mock instance.
func NewMockRoleCache(ctrl *gomock.Controller) *MockRoleCache {
	mock := &MockRoleCache{ctrl: ctrl}
	mock.recorder = &MockRoleCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleCache) EXPECT() *MockRoleCacheMockRecorder {
	return m.recorder
}

// AddIndexer mocks base method.
func (m *MockRoleCache) AddIndexer(arg0 string, arg1 v1.RoleIndexer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddIndexer", arg0, arg1)
}

// AddIndexer indicates an expected call of AddIndexer.
func (mr *MockRoleCacheMockRecorder) AddIndexer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIndexer", reflect.TypeOf((*MockRoleCache)(nil).AddIndexer), arg0, arg1)
}

// Get mocks base method.
func (m *MockRoleCache) Get(arg0, arg1 string) (*v10.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*v10.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoleCacheMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoleCache)(nil).Get), arg0, arg1)
}

// GetByIndex mocks base method.
func (m *MockRoleCache) GetByIndex(arg0, arg1 string) ([]*v10.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIndex", arg0, arg1)
	ret0, _ := ret[0].([]*v10.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIndex indicates an expected call of GetByIndex.
func (mr *MockRoleCacheMockRecorder) GetByIndex(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIndex", reflect.TypeOf((*MockRoleCache)(nil).GetByIndex), arg0, arg1)
}

// List mocks base method.
func (m *MockRoleCache) List(arg0 string, arg1 labels.Selector) ([]*v10.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*v10.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRoleCacheMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoleCache)(nil).List), arg0, arg1)
}
