// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/kubernetes/pkg/registry/rbac/validation (interfaces: AuthorizationRuleResolver)

// Package resolvers is a generated GoMock package.
package mocks

import (
	fmt "fmt"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/rbac/v1"
	user "k8s.io/apiserver/pkg/authentication/user"
)

// MockAuthorizationRuleResolver is a mock of AuthorizationRuleResolver interface.
type MockAuthorizationRuleResolver struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationRuleResolverMockRecorder
}

// MockAuthorizationRuleResolverMockRecorder is the mock recorder for MockAuthorizationRuleResolver.
type MockAuthorizationRuleResolverMockRecorder struct {
	mock *MockAuthorizationRuleResolver
}

// NewMockAuthorizationRuleResolver creates a new mock instance.
func NewMockAuthorizationRuleResolver(ctrl *gomock.Controller) *MockAuthorizationRuleResolver {
	mock := &MockAuthorizationRuleResolver{ctrl: ctrl}
	mock.recorder = &MockAuthorizationRuleResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationRuleResolver) EXPECT() *MockAuthorizationRuleResolverMockRecorder {
	return m.recorder
}

// GetRoleReferenceRules mocks base method.
func (m *MockAuthorizationRuleResolver) GetRoleReferenceRules(arg0 v1.RoleRef, arg1 string) ([]v1.PolicyRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleReferenceRules", arg0, arg1)
	ret0, _ := ret[0].([]v1.PolicyRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleReferenceRules indicates an expected call of GetRoleReferenceRules.
func (mr *MockAuthorizationRuleResolverMockRecorder) GetRoleReferenceRules(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleReferenceRules", reflect.TypeOf((*MockAuthorizationRuleResolver)(nil).GetRoleReferenceRules), arg0, arg1)
}

// RulesFor mocks base method.
func (m *MockAuthorizationRuleResolver) RulesFor(arg0 user.Info, arg1 string) ([]v1.PolicyRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RulesFor", arg0, arg1)
	ret0, _ := ret[0].([]v1.PolicyRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RulesFor indicates an expected call of RulesFor.
func (mr *MockAuthorizationRuleResolverMockRecorder) RulesFor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RulesFor", reflect.TypeOf((*MockAuthorizationRuleResolver)(nil).RulesFor), arg0, arg1)
}

// VisitRulesFor mocks base method.
func (m *MockAuthorizationRuleResolver) VisitRulesFor(arg0 user.Info, arg1 string, arg2 func(fmt.Stringer, *v1.PolicyRule, error) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VisitRulesFor", arg0, arg1, arg2)
}

// VisitRulesFor indicates an expected call of VisitRulesFor.
func (mr *MockAuthorizationRuleResolverMockRecorder) VisitRulesFor(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisitRulesFor", reflect.TypeOf((*MockAuthorizationRuleResolver)(nil).VisitRulesFor), arg0, arg1, arg2)
}
