#!/bin/bash
set -eu

if [ -z "${SHA:-}" ] ; then
  echo "$0 - SHA not set in the environment"
  exit 1
fi

source $(dirname $0)/version

set -x

echo "QQQ: scripts/package: SHA is ${SHA}"
REPO=rancher
IMAGE=${REPO}/webhook:${TAG}
docker tag ${IMAGE} "${REPO}/webhook:${SHA}"
docker save -o dist/rancher-webhook-image-${SHA}.tar "${REPO}/webhook:${SHA}"
