#!/bin/bash
set -e

source $(dirname $0)/version

echo "--- Building and packaging final image ---"

docker build \
    -f package/Dockerfile \
    --build-arg ARCH=${ARCH} \
    --build-arg VERSION=${HELM_CHART_VERSION} \
    --build-arg COMMIT=${COMMIT} \
    -t rancher/webhook:${TAG} \
    .

echo "--- Saving image to tarball ---"
mkdir -p dist
chmod a+rwx dist
docker save -o dist/rancher-webhook-image.tar rancher/webhook:${TAG}
echo IMAGE_TAG=${TAG} > dist/image_tag
