#!/bin/bash

DIRTY=
if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=${COMMIT:-$(git rev-parse --short HEAD)}
GIT_TAG=${GIT_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="0.0.0-${COMMIT}${DIRTY}"
fi

if [ -z "${ARCH:-}" ] ; then
    UNAME_ARCH=$(uname -m)
    if [ "$UNAME_ARCH" = "x86_64" ]; then
        ARCH="amd64"
    elif [ "$UNAME_ARCH" = "aarch64" ]; then
        ARCH="arm64"
    else
        ARCH="$UNAME_ARCH"
    fi
fi

SUFFIX="-${ARCH}"

HELM_TAG="${HELM_TAG:-${TAG:-${VERSION}}}"
HELM_CHART_VERSION="${HELM_CHART_VERSION:-${HELM_TAG/v/}}"
TAG="${TAG:-${VERSION}${SUFFIX}}"
REPO="${REPO:-rancher}"

if echo $TAG | grep -q dirty; then
    TAG=dev
    HELM_TAG=dev
    HELM_CHART_VERSION=0.0.0-dev
fi

DIST_DIR="${DIST_DIR:-$(dirname $0)/../dist/}"
mkdir -p ${DIST_DIR}
echo "export TAG=${TAG}; export HELM_TAG=${HELM_TAG}; export HELM_CHART_VERSION=${HELM_CHART_VERSION};" >${DIST_DIR}/tags
