image:
  repository: rancher/rancher-webhook
  tag: latest
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""
  hostNetwork: false

capi:
  enabled: false

mcm:
  enabled: true

preDelete:
  enabled: true
  image:
    repository: rancher/kubectl
    tag: v1.20.2

nodeSelector: {}

# tolerations for the webhook deployment. See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ for more info
tolerations: []
