image:
  repository: rancher/rancher-webhook
  tag: latest
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""
    psp:
      enabled: true #PSPs enablement should default to true
  hostNetwork: false

capi:
  enabled: false

mcm:
  enabled: true

preDelete:
  enabled: true
  image:
    repository: rancher/kubectl
    tag: v1.23.3

# tolerations for the webhook deployment. See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ for more info
tolerations: []
nodeSelector: {}

## PriorityClassName assigned to deployment.
priorityClassName: ""
